### PR TITLE
Added support for including -ext WixUtilExtension automatically through <extension> build settings

### PR DESCRIPTION
**Pull request by rtksrubie**
in `GetExtensionArguments()`, added a check to add WixUtilExtension to list of  extensions used if attribute `BinaryKey=WixCA` is found in the .wxs document

### CODE REVIEW

**Review by icnocop — APPROVED** [review]

**Comment by rtksrubie** [comment]
@icnocop just so you know, I haven't been able to compile this and test it in the WixEdit project. I'm having issues getting Visual Studio Code on MacOS to build anything. It can't find the msbuild executable.

**Comment by icnocop** [comment]
Thank you for the pull request. 🙂

I don't expect this code to build or run on MacOS because it targets .NET Framework 4.7.2.

**Comment by rtksrubie** [comment]
I tested the change logic as much as I could in [https://dotnetfiddle.net](https://dotnetfiddle.net), so I'm pretty sure it'll do what I want. Just couldn't test the full thing with WixEdit.exe.

Maybe I'll need to put VS Code on the Windows VM and compile it in there. Or make a docker image to build it :)

Thanks for promptly looking at it. I think I typed "-ext WixUtilExtension" 20 times today in that build settings prompt. Looks like  the github actions will make a new release that I can try?

**Comment by icnocop** [comment]
> Looks like the github actions will make a new release that I can try?

Yes, please try the fix in [v0.8.1417.11](https://github.com/WixEdit/WixEdit/releases/tag/v0.8.1417.11)

Thank you.

**Pull request merged**
